### ISSUE TITLE
Group list filter key issue

### ISSUE THREAD

**Issue by ValtielChan** [mailerlite/mailerlite-python#12]
Hey !

In group.py, line 29, you check if the key is in available_params, but if you use the key "filter", it raise an error because "filter" is not in available_params and the case key=="filter" is handled after this error. So you can't use the key filter with group listing.

**Comment by aidanpl** [comment]
Have just come across the same issue. Should 'filter' be in the list of available_params or is it deliberately not there while this API is under development?

**Comment by igorhrcek** [comment]
Hi @ValtielChan! 
Thank you for your submission, this was an omission on our end. This issue is now resolved and the fix will be released soon.
