### ISSUE TITLE
Forget API is not implemented for subscribers

### ISSUE THREAD

**Issue by jocelynthode** [mailerlite/mailerlite-python#14]
The Forget api call: https://developers.mailerlite.com/docs/subscribers.html#forget-a-subscriber is not implemented for subscribers which is a problem as the sdk does not currently allow for a GDPR compliant delete.

If you take PRs I could work on this.

**Comment by igorhrcek** [comment]
Hi @jocelynthode!

Thank you for your submission, that API endpoint is relatively new and it is now being implemented.
