### ISSUE TITLE
get_group_subscribers filter params does not work as intended

### ISSUE THREAD

**Issue by jocelynthode** [mailerlite/mailerlite-python#15]
Hey, the `filter` param for `get_group_subscribers` does not work as intended.

the doc specifies to user `filter={'status': 'active'}` however, the code here: https://github.com/mailerlite/mailerlite-python/blob/main/mailerlite/sdk/groups.py#L143 expects the paramter in the following format:
```
filter={'filter[status]': 'active'}
```

I have not checked whether this bugs happens on other functions as well.

**Comment by codebykyle** [comment]
Hello, 

This ticket appears to be marked as invalid, but is indeed a valid issue.

Per the Mailerlite documentation here:
https://developers.mailerlite.com/docs/groups.html#list-all-groups

The expected parameter is filter[name]

The documentation in the readme here:
https://github.com/mailerlite/mailerlite-python?tab=readme-ov-file#list-all-groups

specifies that the filter parameter be in the format of:
`response = client.groups.list(limit=10, page=1, filter={'name': 'My'}, sort='name')`

This code will return all groups, as the filter parameter is ignored.

The list function on groups (as an example) just appends the filter to the query parameters directly, without modification:

```python
    def list(self, **kwargs):
        """
        Lists all groups

        Returns a list of all groups.
        Ref: https://developers.mailerlite.com/docs/groups.html#list-all-groups

        :param **kwargs: You can pass additional arguments - page, limit, sort or to filter by name
        :raises: :class: `TypeError` : Got an unknown argument
        :return: JSON array
        :rtype: dict
        """

        available_params = ["list", "limit", "page", "sort", "filter"]

        params = locals()
        query_params = {}
        for key, val in params["kwargs"].items():
            if key not in available_params:
                raise TypeError("Got an unknown argument '%s'" % key)
            if key == "filter":
                for filter_key, filter_value in val.items():
                    query_params[filter_key] = filter_value
            else:
                query_params[key] = val

        return self.api_client.request("GET", self.base_api_url, query_params).json()
```
        
For example:
        
        
![image](https://github.com/mailerlite/mailerlite-python/assets/26160129/c3a206e8-c7c8-4fba-89ed-cef63b50828b)

As a suggested fix, the loop in list should be updated to something similar to:

```
        for key, val in params["kwargs"].items():
            if key not in available_params:
                raise TypeError("Got an unknown argument '%s'" % key)
            if key == "filter":
                for filter_key, filter_value in val.items():
                    query_params['filter[%s]' % filter_key] = filter_value
            else:
                query_params[key] = val
```

**Comment by jptreen** [comment]
Hey!

I had this issue, but with segments. I think the specific issue here has been closed now, but it's present in other endpoints.

I made a more generalised fix to this type of issue in my PR, getting rid of a lot of duplicate code.

https://github.com/mailerlite/mailerlite-python/pull/28
