### ISSUE TITLE
Only v1.2 on PyPI

### ISSUE THREAD

**Issue by andre-fuchs** [mailerlite/mailerlite-python#26]
Hello,
I just tried to add this package to a virtual environment via PIP and got the version 1.2 only. See [pypi.org/project/mailerlite-python/](https://pypi.org/project/mailerlite-python/). Doen’t look very official as well. Or is this another package with the same name? I am confused.

**Comment by robgordon89** [comment]
the package that we provide here is simply called mailerlite 

```
python -m pip install mailerlite
```

Thanks 
Bob
