### ISSUE TITLE
Incorrect Endpoint for "Get subscribers belonging to a segment"

### ISSUE THREAD

**Issue by onAutopylot** [mailerlite/mailerlite-python#30]
typo results in incorrect endpoint for request:

segment.py
Line 68
missing '/subscribers' at the end to ensure subscribers of a segment are retrieved

Currently retrieves the segment, not the subscribers of the segment.

**Comment by igorhrcek** [comment]
Hi @onAutopylot 👋 

Thank you for reporting this issue. It's been addressed in the [v0.1.8](https://github.com/mailerlite/mailerlite-python/releases/tag/v0.1.8)
