### ISSUE TITLE
Unable to paginate subscribers

### ISSUE THREAD

**Issue by jmathai** [mailerlite/mailerlite-python#31]
I'm trying to paginate through subscribers but the `page` parameter seems to be ignored resulting in my attempts to do so using a `while True:` loop from running endlessly.

Furthermore, the API docs indicate that the API uses [cursor](https://developers.mailerlite.com/docs/subscribers.html#list-all-subscribers) or [offset](https://developers-classic.mailerlite.com/reference/subscribers) based pagination but the SDK uses pages.

Here's a simple code example and output.

```python
for page in range(1,5):
    subscribers_response = client.subscribers.list(limit=1, page=page)
    print("{} | {}".format(page, subscribers_response['data'][0]['id']))
```

```
1 | 133455531183441619
2 | 133455531183441619
3 | 133455531183441619
4 | 133455531183441619
```

**Comment by igorhrcek** [comment]
Hi @jmathai 👋  
Thank you for reporting this issue. It has been [resolved in v0.1.9](https://github.com/mailerlite/mailerlite-python/releases/tag/v0.1.9)
